// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PI4.Data;

#nullable disable

namespace PI4.Migrations
{
    [DbContext(typeof(VideoSubjectDbContext))]
    partial class VideoSubjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("OnderwerpVideo", b =>
                {
                    b.Property<int>("OnderwerpenOnderwerpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideosVideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OnderwerpenOnderwerpId", "VideosVideoId");

                    b.HasIndex("VideosVideoId");

                    b.ToTable("OnderwerpVideo");
                });

            modelBuilder.Entity("PI4.Models.Onderwerp", b =>
                {
                    b.Property<int>("OnderwerpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("TEXT");

                    b.HasKey("OnderwerpId");

                    b.ToTable("Onderwerpen");
                });

            modelBuilder.Entity("PI4.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("OnderwerpVideo", b =>
                {
                    b.HasOne("PI4.Models.Onderwerp", null)
                        .WithMany()
                        .HasForeignKey("OnderwerpenOnderwerpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PI4.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("VideosVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
